name: Build Test

on:
  pull_request:
    branches: [dev, master]

jobs:
  build:
    runs-on: ubuntu-latest

    # Set the working directory for all steps in this job
    defaults:
      run:
        working-directory: backhaul-xcien

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backhaul-xcien/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
